config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  template_dotfile_default: false
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    template: true
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    upignore:
    - '*/lazy-lock.json'
    cmpignore:
    - '*/lazy-lock.json'
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  d_local_zsh:
    src: local/share/zsh
    dst: ~/.local/share/zsh
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    template: true
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
    template: true
  d_htop:
    src: config/htop
    dst: ~/.config/htop
  d_atuin:
    src: config/atuin
    dst: ~/.config/atuin
  d_vifm:
    src: config/vifm
    dst: ~/.config/vifm
    upignore:
    - '*/vifm-help.txt'
    - '*/vifminfo*'
    cmpignore:
    - '*/vifm-help.txt'
    - '*/vifminfo*'
  d_local_bin:
    src: local/bin
    dst: ~/.local/bin
  d_gotop:
    src: config/gotop
    dst: ~/.config/gotop
  d_tmux:
    src: config/tmux
    dst: ~/.config/tmux
    upignore:
    - '*/plugins/*'
    cmpignore:
    - '*/plugins/*'
  d_tmuxp:
    src: config/tmuxp
    dst: ~/.config/tmuxp
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_terminal-colors.d:
    src: config/terminal-colors.d
    dst: ~/.config/terminal-colors.d
  f_zlogin:
    src: zlogin
    dst: ~/.zlogin
  d_vivid:
    src: config/vivid
    dst: ~/.config/vivid
  f_roficlip_persistent.db:
    src: local/share/roficlip/persistent.db
    dst: ~/.local/share/roficlip/persistent.db
  d_roficlip:
    src: config/roficlip
    dst: ~/.config/roficlip
    actions:
      - pull_roficlip
profiles:
  meta-base:
    dotfiles:
    - f_zshrc
    - d_local_bin
    - d_local_zsh
    - f_starship.toml
    - d_atuin
    - f_gitconfig
    - d_nvim
    - d_vifm
    - d_tmux
    - d_bat
    - d_terminal-colors.d
    - d_vivid
  seamus-lxc:
    include:
    - meta-base
    dotfiles:
    - d_neofetch
    - d_htop
    - d_gotop
    - d_tmuxp
  garuda-seamus:
    include:
    - meta-base
    dotfiles:
    - f_zlogin
    - f_roficlip_persistent.db
    - d_roficlip
variables:
  apps_bin: "${{HOME}}/.local/apps/bin"
  git_installed: (test -x /usr/bin/git)
  roficlip_path: "${{HOME}}/.local/apps/roficlip/"
  roficlip_url: "https://github.com/seamus-45/roficlip.git"
  roficlip_ne: (test ! -d "{{@@ roficlip_path @@}}")
actions:
  pull_roficlip: "{{@@ git_installed @@}} && {{@@ roficlip_ne @@}} && (mkdir -p {{@@ apps_bin @@}}; git clone {{@@ roficlip_url @@}} {{@@ roficlip_path @@}}; ln -s ../roficlip/roficlip.py {{@@ apps_bin @@}}) ||:"
