config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
    upignore:
    - '*/lazy-lock.json'
    cmpignore:
    - '*/lazy-lock.json'
  d_neofetch:
    src: config/neofetch
    dst: ~/.config/neofetch
  d_local_zsh:
    src: local/share/zsh
    dst: ~/.local/share/zsh
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_htop:
    src: config/htop
    dst: ~/.config/htop
  d_atuin:
    src: config/atuin
    dst: ~/.config/atuin
  d_vifm:
    src: config/vifm
    dst: ~/.config/vifm
    upignore:
    - '*/vifm-help.txt'
    - '*/vifminfo*'
    cmpignore:
    - '*/vifm-help.txt'
    - '*/vifminfo*'
  d_local_bin:
    src: local/bin
    dst: ~/.local/bin
  d_gotop:
    src: config/gotop
    dst: ~/.config/gotop
  d_tmux:
    src: config/tmux
    dst: ~/.config/tmux
    upignore:
    - '*/plugins/*'
    cmpignore:
    - '*/plugins/*'
  d_tmuxp:
    src: config/tmuxp
    dst: ~/.config/tmuxp
  d_bat:
    src: config/bat
    dst: ~/.config/bat
  d_terminal-colors.d:
    src: config/terminal-colors.d
    dst: ~/.config/terminal-colors.d
  f_zlogin:
    src: zlogin
    dst: ~/.zlogin
profiles:
  meta-base:
    dotfiles:
    - f_zshrc
    - d_local_bin
    - d_local_zsh
    - f_starship.toml
    - d_atuin
    - f_gitconfig
    - d_nvim
    - d_vifm
    - d_tmux
    - d_bat
    - d_terminal-colors.d
  seamus-lxc:
    include:
    - meta-base
    dotfiles:
    - d_neofetch
    - d_htop
    - d_gotop
    - d_tmuxp
  garuda-seamus:
    include:
    - meta-base
    dotfiles:
    - f_zlogin
