---
session_name: ansible
windows:
  - window_name: M
    start_directory: "~/gitlab/ansible-molecule"
    panes:
      - shell_command:
        - source ./venv/bin/activate
      - shell_command:
        -
  - window_name: A0
    start_directory: "~/gitlab"
    panes:
      -
  - window_name: A1
    start_directory: "~/gitlab"
    panes:
      -
