# based on molokai

colors:
  # Theme colors
  background_color: '1a1a1a'
  purple: "ae81ff"
  khaki: "e6db74"
  pink: "f92672"
  cyan: "66d9ef"
  cyan2: "60ef89"
  blue: "60aeef"
  green: "a6e22e"
  orange: "fd971f"

  # Others
  white: "ffffff"
  black: "000000"
  red: "ff4a44"
  gray: "b6b6b6"
  dimgray: "7a7070"
  gold: "e2d139"
  springgreen: "00ff87"
  lightgreen: "abff1a"
  darkgray: "333333"

core:
  normal_text: {}
  regular_file: {}
  reset_to_normal: {}

  directory:
    foreground: cyan

  symlink:
    foreground: cyan2
    font-style: bold

  multi_hard_link: {}

  fifo:
    foreground: purple
    font-style: bold

  socket:
    foreground: purple
    font-style: bold

  door:
    foreground: black
    background: pink

  block_device:
    foreground: gold

  character_device:
    foreground: pink

  broken_symlink:
    foreground: red

  missing_symlink_target:
    foreground: red

  setuid: {}

  setgid: {}

  file_with_capability: {}

  sticky_other_writable: {}

  other_writable: {}

  sticky: {}

  executable_file:
    foreground: lightgreen
    font-style: bold

text:
  special:
    foreground: gold
    font-style: bold

  todo:
    font-style: bold

  licenses:
    foreground: gray

  configuration:
    foreground: green

  other:
    foreground: gold

markup:
  foreground: gold

programming:
  source:
    foreground: springgreen

  tooling:
    foreground: green

    continuous-integration:
      foreground: khaki

media:
  foreground: orange
  image:
    foreground: blue

office:
  foreground: khaki

archives:
  foreground: pink
  font-style: underline

executable:
  foreground: lightgreen
  font-style: bold

unimportant:
  foreground: dimgray
